// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/api/generate-wp-rest-api-types.ts";
import * as $1 from "./routes/index.tsx";
import * as $2 from "./routes/tachyon-playground.tsx";
import * as $3 from "./routes/wp-rest-api-typescript.tsx";
import * as $$0 from "./islands/TachyonPlayground.tsx";
import * as $$1 from "./islands/WPRestApiTypeScriptTypeGenerator.tsx";

const manifest = {
  routes: {
    "./routes/api/generate-wp-rest-api-types.ts": $0,
    "./routes/index.tsx": $1,
    "./routes/tachyon-playground.tsx": $2,
    "./routes/wp-rest-api-typescript.tsx": $3,
  },
  islands: {
    "./islands/TachyonPlayground.tsx": $$0,
    "./islands/WPRestApiTypeScriptTypeGenerator.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
