// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/2023-01-tough-month-at-human-made.tsx";
import * as $1 from "./routes/api/generate-wp-rest-api-types.ts";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/learning-rust-the-hard-way.tsx";
import * as $4 from "./routes/tachyon-playground.tsx";
import * as $5 from "./routes/wp-rest-api-typescript.tsx";
import * as $6 from "./routes/x/wp-api-types.ts.ts";
import * as $$0 from "./islands/TachyonPlayground.tsx";
import * as $$1 from "./islands/WPRestApiTypeScriptTypeGenerator.tsx";

const manifest = {
  routes: {
    "./routes/2023-01-tough-month-at-human-made.tsx": $0,
    "./routes/api/generate-wp-rest-api-types.ts": $1,
    "./routes/index.tsx": $2,
    "./routes/learning-rust-the-hard-way.tsx": $3,
    "./routes/tachyon-playground.tsx": $4,
    "./routes/wp-rest-api-typescript.tsx": $5,
    "./routes/x/wp-api-types.ts.ts": $6,
  },
  islands: {
    "./islands/TachyonPlayground.tsx": $$0,
    "./islands/WPRestApiTypeScriptTypeGenerator.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
